dir = Pathname(__FILE__).dirname.expand_path / 'support'

require dir / 'errors'
require dir / 'inflection'
require dir / 'kernel'
require dir / 'lazy_array'
require dir / 'object'
require dir / 'pathname'
require dir / 'string'
require dir / 'symbol'
